optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 100
  batch_size: 4096
  save_model: true
  loss: pairwise
  test_step: 3
  reproducible: true
  seed: 2023
  patience: 5

test:
  metrics: [recall, ndcg, mrr] # choose in {ndcg, recall, precision, mrr}
  k: [5, 10, 20, 40, 100] # top-k
  batch_size: 1024 # How many users per batch during validation

data:
  type: general_cf
  name: amazon_music


model:
  name: gccf
  keep_rate: 0.8
  embedding_size: 32
  layer_num: 2
  reg_weight: 1.0e-6
  