optimizer:
  name: adam
  lr: 1.0e-3 # not 1e-3
  weight_decay: 0

train:
  epoch: 300
  batch_size: 4096
  save_model: false
  loss: pairwise # bpr
  log_loss: false # whether to log loss
  test_step: 5 # evaluate per {test_step} epochs
  patience: 5
  reproducible: true
  seed: 1
  cuda: 5
  #pretrain_path: ./checkpoint/xxxx.pth
  kg_path: ../dataset/Douban/KG.pkl
  pretrain_config: ../save/Douban-LR0.0003-MU0.1-Temp0.5-new
  checkpoint: epoch-5

test:
  metrics: [recall, ndcg, mrr] # choose in {ndcg, recall, precision, mrr}
  k: [5, 10, 20, 40, 100] # top-k
  batch_size: 1024 # How many users per batch during validation

data:
  type: general_cf # choose in {general_cf, multi_behavior, sequential, social}
  name: douban_movie


model:
  name: ncf_pt # case-insensitive
  keep_rate: 0.5
  layer_num: 2
  reg_weight: 1.0e-8
  embedding_size: 32

tune:
  enable: false # Whether to enable grid search to search for optimal hyperparameters
  hyperparameters: [reg_weight] # The name of the hyperparameter
  reg_weight: [1.0e-8, 1.0e-9, 1.0e-7]
