optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 120
  batch_size: 4096
  save_model: false
  loss: pairwise
  log_loss: false
  test_step: 3
  patience: 5
  reproducible: true
  seed: 2023

test:
  metrics: [recall, ndcg, mrr]
  k: [5, 10, 20, 40, 100]
  batch_size: 1024

data:
  type: general_cf
  name: douban_book

model:
  name: simgcl
  keep_rate: 1.0
  layer_num: 2
  reg_weight: 1.0e-6
  cl_weight: 1.0e-3
  temperature: 0.1
  embedding_size: 32
  eps: 0.9

tune:
  enable: false
  hyperparameters: [layer_num, cl_weight, temperature, eps]
  layer_num: [2, 3]
  cl_weight: [1.0e-1, 1.0e-2, 1.0e-3]
  temperature: [0.1, 0.2, 0.5, 1.0]
  eps: [0.1, 0.2, 0.5, 0.9]
  # reg_weight: [1.0e-5, 1.0e-6, 1.0e-7] (optional)
